### ISSUE TITLE
[NOT DUPLICATE] Can't backup or deactivate specifically Geode in SideStore

### ISSUE THREAD

**Issue by ryder7223** [geode-sdk/ios-launcher#22]
![Image](https://github.com/user-attachments/assets/0ee9af7d-5ca4-4bbe-8cec-1d1ffdacfcd2)

As deactivating an app requires backing up, I cannot deactivate Geode via SideStore or back it up.

Here is the error:
```
“Geode” couldn’t be copied because you don’t have permission to access “com.robtop.geometryjump.app”.

To view or change permissions, select the item in the Finder and choose File > Get Info.
```

I have seen a similar issue appear when repurposing my online to local level transfer python script to work on geode, which edits the local levels save file, and even with sudo privileges it would say permission denied.

**Comment by Alphalaneous** [comment]
Update the launcher

**Comment by ryder7223** [comment]
> Update the launcher

It is already on 0.4.0

**Comment by FireMario211** [comment]
This is similar to https://github.com/geode-sdk/ios-launcher/issues/20

If you did download the latest build artifact, launch the app once, then deactivate

**Comment by ryder7223** [comment]
I have tried the solution from issue 20, but it has not worked, it does say in geode that the app is deactivated in the sense that it is overridden by the teel deactivated screen, but it is not deactivated in SideStore.

When SideStore tried to open Geode as part of the deactivation process, the following error occurs, and then the previously shown error occurs in SideStore.
![Image](https://github.com/user-attachments/assets/2bfa2052-23c0-48f7-98b3-aea7c9bf82c5)

**Comment by FireMario211** [comment]
@ryder7223 I'm assuming this is resolved after the update came out? I saw you made an issue for LiveContainer so I'm assuming you were able to deactivate Geode in favor of LiveContainer, but not sure.

**Comment by ryder7223** [comment]
@FireMario211 I manually copied the data file out of Geode, and uninstalled it from the home screen, I tried LiveContainer instead, this issue still persists.

**Comment by FireMario211** [comment]
I unfortunately cannot reproduce the issue, plus it has been 2 months later so I assume it either has disappeared or no one has encountered it in a while.
